### ISSUE TITLE
Brightcove video embed component not importing and displaying

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/helix-sportsmagazine#11]
This one was found by William.  Video embeds within the article body are not importing. 

![image](https://user-images.githubusercontent.com/51373617/206569526-734e9281-b5d5-4b2a-b04f-f7efde7e98de.png)

**Comment by mckeehan** [comment]
Example page with these Brightcove videos on it: https://www.golfdigest.com/story/desert-golf-how-to-play

**Comment by hsaginor** [comment]
I opened a new ticket to change brightcove implementation to not use ifame https://github.com/headwirecom/helix-sportsmagazine/issues/22. Closing this
