### ISSUE TITLE
Fullbleed editor's note support

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#118]
Some articles start with Editor's Note eg on https://www.golfdigest.com/story/favorite-golf-insiders-tv-broadcasters-personalities-reporters-power-poll

<img width="807" alt="Screenshot 2023-08-07 at 17 18 18" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/2fb44c56-4253-4370-85df-5876d4437652">

We could support it with eg a document wide metadata field

**Comment by hsaginor** [comment]
@icaraps do we need import changes for this?
