### ISSUE TITLE
Fullbleed article not able to render youtube embed link

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#119]
For example on https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/gerry-mcilroy-bet-rory-mcilroy-british-open-2023 the youtube embed isn't loading because it was not imported cc @hsaginor

**Comment by icaraps** [comment]
Ok will look into the 2nd issue a bit more

**Comment by hsaginor** [comment]
@icaraps 
I reimported the document https://docs.google.com/document/d/1bU0T0oSkFIFeopGSIVQD31sYS7tN1vqp2RxVDwwZHnE/edit
The imported link appears to be correct https://www.youtube.com/embed/yVuVnu74i5A

You might want to check the rendering code. The importer imports it correctly.

**Comment by icaraps** [comment]
@hsaginor  You're right it must be the embed block that is messing up the rendering. I renamed the ticket accordingly 👍
