### ISSUE TITLE
Templates, page properties and display rules for pages

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/helix-sportsmagazine#12]
Templates

![image](https://user-images.githubusercontent.com/51373617/207977719-0199a85f-a21f-4a85-8e1b-9549d2fbc30b.png)

Page Properties

![image](https://user-images.githubusercontent.com/51373617/207977896-1f9d93f9-5248-46cd-ad45-1689fd891c30.png)

![image](https://user-images.githubusercontent.com/51373617/207977933-14ae3a12-4450-4ec7-9cfc-f2608da357f2.png)

Display Rules

**Comment by hsaginor** [comment]
Some examples
1) Full Bleed article 
https://github.com/headwirecom/helix-sportsmagazine/issues/8 
https://www.golfdigest.com/content/golfdigest-com/en/golf-news-tours/features/article/2022/10/asia-pacific-amateur-2022-preview-major-invites-masters-emerging-golf-nations.html

**Comment by hsaginor** [comment]
@icaraps Is this outdate? I think we are using Franklin templates now.

**Comment by icaraps** [comment]
Yes looks like we still have a couple of templates to build out
