### ISSUE TITLE
Implement content migration tools as separate project.

### ISSUE THREAD

**Issue by hsaginor** [headwirecom/helix-sportsmagazine#121]
We should decouple content migration scripts/tools from the web site project and implement the following enhancements.

1. Create a CLI tool. The browser UI doesn't work well for a large content import.
2. A way to crawl the site and import directly from sitemap. We have a script now that should be enhanced.
3. Investigate possibilities for integrating directly with google drive upload. Manual process is long and cumbersome  

Content import issues should be fixed in this separate project - https://github.com/headwirecom/helix-sportsmagazine/labels/Import

**Comment by hsaginor** [comment]
@icaraps WDYT?

**Comment by icaraps** [comment]
@hsaginor agree this will help to iterate much faster when we find importer issues and not only for this project but also for future migration projects

**Comment by hsaginor** [comment]
@icaraps so I started this [franklin-importer-tools](https://github.com/headwirecom/franklin-importer-tools)

**Comment by hsaginor** [comment]
Content migration related tools and script are implemented as new projects in github now:

- https://github.com/headwirecom/franklin-importer-tools
- https://github.com/headwirecom/sportsmagazine-content-migration
