### ISSUE TITLE
Ceros embed iframe url not imported for longform articles

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#128]
For example on https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/7/genesis-scottish-open-picks-2023

There's a [ceros embed](https://view.ceros.com/golf-digest/expert-picks-1-1-2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-2-1-1-1-1-1-1-1-2-1-1-1-1-1-1-1-1-1-1-2-1-1-1-1-1-2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-2-1-1-1-1-1-1-1-1-1-1-1-1-1-2-1-1-2-1-1-1-1-1-1-1-1-1-1/p/1) that displays golf result. That is completely missing in the imported document.

<img width="967" alt="Screenshot 2023-08-08 at 14 07 14" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/94fe8dc4-448f-43eb-9aa5-a50cec59501b">

**Comment by icaraps** [comment]
cc @hsaginor

**Comment by hsaginor** [comment]
@icaraps I think this is just a general iframe embed. So, this could be any content. We can probably put an "embed" block there with a link

**Comment by hsaginor** [comment]
Here is an example of an imported document for this page Embed block
[genesis-scottish-open-picks-2023.docx](https://github.com/headwirecom/helix-sportsmagazine/files/12384270/genesis-scottish-open-picks-2023.docx)

There are actually 2 embed like this on this page. The other one is the apple podcast.

**Comment by hsaginor** [comment]
@icaraps Closing this. The importer will place an explicit embed block for miscellaneous iframes to external content.
