### ISSUE TITLE
Longform article photo credits or author credits not always imported

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#132]
For example for https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/6/rocket-mortgage-classic-picks-2023, "Stacy Severe" photo credit was not imported cc @hsaginor

**Comment by hsaginor** [comment]
Fixed. 
Reimported document
https://docs.google.com/document/d/1Oe_yctqyQBEiRxyw3sirD3blXPFtyPmOQvA-bu-meyI/edit
https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/the-loop/gambling/article/2023/6/rocket-mortgage-classic-picks-2023

Full reimport will be needed to fix it everywhere.
