### ISSUE TITLE
Twitter embed short form variant support

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#140]
In some articles like https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/3m-open-erik-van-rooyen-alex-gaugert-caddie-monday-qualifier-playing-together, the twitter embed should be displayed without media

<img width="753" alt="Screenshot 2023-08-08 at 15 48 51" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/8335bd10-41fe-4e68-9554-22ffd3e24888">

Maybe we can introduce an embed twitter variation for it (eg with a class)

**Comment by Lauraa1003** [comment]
I looked into the Twitter embed problem. It seems the missing media was likely a bug on GD’s end.  I can’t find this media issue anymore on the GD site, looks like they've addressed it. I suggest we close this issue now.
