### ISSUE TITLE
articles have no GD+ indicator

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#152]
article-query-index articles have no indication if they are GD+ or not
https://docs.google.com/spreadsheets/d/1b3-S_L_X53F6kgLlcfSAFYY28dMWSgmRrtTLxxWgL2U/

**Comment by hsaginor** [comment]
@DriftingSands @icaraps Is this the only missing data in the index. Do, we need anything else. We should probably have a ticket to identify all of them so we don't need to keep reimporting 70K+ pages. Well in this case it's probably only articles but it's still a large import every time.

**Comment by DriftingSands** [comment]
@hsaginor I have been working on replacing mock data for the landing page and here are a few more data entries that I noticed were missing.

The heros & cards have a short title, I've been using the rubric but it is often missing:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/65e7e49c-7c12-4aea-b7fa-1a87c076f6b6)

Courses carousel have locations, reward tags and public/private flag that we also need:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/449baf59-eb6e-4e84-b7eb-e572efad98e2)

Lots of articles image path is: `/default-meta-image.png` which doesn't lead anywhere:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/61be7534-89e3-4007-8702-4e47002c171b)

There is also no alt-text for images

**Comment by hsaginor** [comment]
@DriftingSands Thank you! I will check what else we can pull from the original site. We should probably use the same content.

**Comment by hsaginor** [comment]
@DriftingSands So, on the original site I am seeing rubric used as "short title" and long title as title for these. At least that's what I see. Or can you please provide some page references in our Franklin site and the original?

For GD+ I am adding GD Plus page metadata field set to "yes" if it's a GD+ page (at least if the importer script can guess). It sounds like their technical team are not sure how to determine that reliably from their markup. So, the index will have "gd-plus" field once we update it. Let me know if we need to change it. I don't know what your mock data has.

**Comment by icaraps** [comment]
@hsaginor can you pls also update the `helix-query.yaml` accordingly ?

**Comment by hsaginor** [comment]
@icaraps I will add with the importer changes. Then we need to reimport/reindex all content and update index google sheets.

**Comment by hsaginor** [comment]
@icaraps @DriftingSands The gdPlus indicator has been added. Although, we have not reimported content yet. So, that field will be empty in most cases.

For courses carousel I am not really sure what to do yes since we have not been importing courses pages yet (and/or rendering them). I suggest we have a separate ticket for them and decide there what specific content needs to be imported.

**Comment by icaraps** [comment]
> I suggest we have a separate ticket for them and decide there what specific content needs to be imported.

+1 Feel free to open an importer ticket for it.
