### ISSUE TITLE
Image caption not imported as metadata in the article body

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#171]
For example: 
* https://www.golfdigest.com/story/bryan-kim-wins-2023-us-junior-amateur-over-joshua-bai-2-up
* https://www.golfdigest.com/story/liv-golf-owgr-delay

<img width="846" alt="Screenshot 2023-08-21 at 10 07 38" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/4f248ff2-bcf6-4fe4-bcae-d8251f2cf8e6">
<img width="868" alt="Screenshot 2023-08-21 at 10 07 49" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/d4683ab2-e1c1-499e-8b2f-3ea41d24aa0c">

**Comment by hsaginor** [comment]
@icaraps I am fine with "Photo Caption". But it also looks like we missing these imageEmbed in the article body. So, I am creating a section for each of them if they have metadata (aka photo credit and caption). We could create blocks but I wanted to be consistent with our current approach of avoiding blocks if we can.

See attached documents and let me know if this works -
[bryan-kim-wins-2023-us-junior-amateur-over-joshua-bai-2-up.docx](https://github.com/headwirecom/helix-sportsmagazine/files/12403273/bryan-kim-wins-2023-us-junior-amateur-over-joshua-bai-2-up.docx)
[liv-golf-owgr-delay.docx](https://github.com/headwirecom/helix-sportsmagazine/files/12403277/liv-golf-owgr-delay.docx)

**Comment by icaraps** [comment]
@hsaginor perfect thanks !
