### ISSUE TITLE
Support courses block

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#177]
For example here https://www.golfdigest.com/story/pine-valley-curtis-cup or https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/_default/article/2023/7/here-is-the-prize-money-payout-for-each-golfer-at-the-2023-3m-open

![image](https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/4618c752-f7d2-4061-94ef-86948ceeea97)

**Comment by icaraps** [comment]
We can also start by defining and creating the block for it and then once that's done, make sure the importer identifies and create the table for that block.

**Comment by icaraps** [comment]
@hsaginor this new block will also require some changes in the importer so it can detect this type of content and create the corresponding table.

**Comment by hsaginor** [comment]
@icaraps We should discuss importing referenced content. This could be a block with just a reference or just a link to a course page (like https://www.golfdigest.com/places-to-play/nj/pine-valley-golf-club)

**Comment by icaraps** [comment]
@hsaginor  +1 feel free to open an importer ticket for it.
