### ISSUE TITLE
Image Import Issue

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/helix-sportsmagazine#18]
Adding this to provide more info once gathered.

Basically, image renditions from AEM are not accurately importing into Franklin. This is seen most prevalently in galleries, where a horizontal image that fills the slide is importing as a vertical image that does not fill the slide. It is also seen less so in listicles and general articles wherein an image that has a large original size that is renditioned down to fit the page/component, is importing as the lesser quality image and size in the Franklin page. This is leading to degradation in the image quality as well as messing with the desired gallery display. 

Examples: 

![Screenshot_20230209_033435](https://user-images.githubusercontent.com/51373617/218570647-9179941e-9cf4-4c3a-a2eb-959e9b3caef7.png)

![Screenshot_20230209_033649](https://user-images.githubusercontent.com/51373617/218570690-ccfda796-77b4-4c4c-a504-594ee069ea14.png)

![Screenshot_20230209_033451](https://user-images.githubusercontent.com/51373617/218570755-bb4d6c31-295e-4109-a789-16ad32b23c26.png)

**Comment by ehdatheadwire** [comment]
Updated based on 2/14/23 call: 
- Henry to remove the rend portion of the image URL
- Henry to adjust import so that it is pulling in OG image
- Henry to re-run the import for all galleries/listicles

**Comment by hsaginor** [comment]
@icaraps I am not sure if this ticket is valid. We are importing original images now. And the particular document mentioned in this ticket now fails to upload to GD due to file size. This is a separate issue we need to address by referencing images instead of storing them in the document

**Comment by hsaginor** [comment]
Closing this ticket. The following has been done a while ago. 
- Henry to remove the rend portion of the image URL
- Henry to adjust import so that it is pulling in OG image
- Henry to re-run the import for all galleries/listicles
