### ISSUE TITLE
Support vanity path at the edge

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#186]
This is an exploration ticket. This is about making vanity path work in the most performant way. For example, a URL like https://www.golfdigest.com/story/xander-schauffele-on-closing-62-east-lake-2023-most-fun-had-losing-quite-some-time should render the page in the content folder `/content/x/y/z/xander-schauffele-on-closing-62-east-lake-2023-most-fun-had-losing-quite-some-time`

We can use a free cloudflare account with a worker that has the mapping sorted out.

**Comment by hsaginor** [comment]
@icaraps Do you have any ideas about vanity URLs? How would this affect rewriting links in the importer or links in a google document.

**Comment by icaraps** [comment]
@hsaginor  I was thinking the following : 
* Build a cron job that retrieves all urls from the indexes and create a mapping for it
* Create a service that leverages that mapping to return the right page for a given vanity url

If this works well, we don't have to change anything in the importer related to vanity urls.

**Comment by icaraps** [comment]
> It looks like I won't need the cron job, I can simply reuse the different indexes we have: article, product and gallery.

Unfortunately it can take several seconds to get the whole index (~2s for 10000 items) on `hlx.live` ... So I'll go back to my initial proposal with the cron job which is also supported by cloudflare https://developers.cloudflare.com/workers/configuration/cron-triggers/. It's basically a worker that is executed on a schedule.

**Comment by icaraps** [comment]
Seems like this option could work https://www.hlx.live/developer/github-actions

**Comment by icaraps** [comment]
So another issue with vanity paths once it's actually working is to fix the image relative paths ...

<img width="1099" alt="Screenshot 2023-09-07 at 18 48 57" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/ea6ae8fd-b2d3-4b01-86a5-bfc107580bd1">
