### ISSUE TITLE
importing course pages

### ISSUE THREAD

**Issue by hsaginor** [headwirecom/helix-sportsmagazine#224]

**Comment by hsaginor** [comment]
@icaraps What content should we be importing from these pages? Do we need blocks for About and address/contact?

Here are some examples
1 https://www.golfdigest.com/places-to-play/3s-greenville-3s-course
2 https://www.golfdigest.com/places-to-play/anne-arundle-manor-anne-arundle
3 https://www.golfdigest.com/places-to-play/aquarina-beach-and-country-club-aquarina-front-9
4 https://www.golfdigest.com/places-to-play/arcadia-bluffs-south-course-south-course
5 https://www.golfdigest.com/places-to-play/babcock-national-at-babcock-ranch-babcock-national
6 https://www.golfdigest.com/places-to-play/bar-run-golf-bar-run-front-9
7 https://www.golfdigest.com/places-to-play/bayou-oaks-at-city-park-south-course-south-course
8 https://www.golfdigest.com/places-to-play/blackwolf-run-the-baths
9 https://www.golfdigest.com/places-to-play/carlisle-golf-course-carlisle-9
10 https://www.golfdigest.com/places-to-play/colin-creek-golf-club-colin-creek
11 https://www.golfdigest.com/places-to-play/coonskin-park-golf-course-front-9
12 https://www.golfdigest.com/places-to-play/copper-canyon-golf-club-lake
13 https://www.golfdigest.com/places-to-play/copper-canyon-golf-club-mountain
14 https://www.golfdigest.com/places-to-play/cross-creek-golf-club-cross-creek-9
15 https://www.golfdigest.com/places-to-play/cutalong-at-lake-anna-cutalong
16 https://www.golfdigest.com/places-to-play/desert-mountain-club-seven
17 https://www.golfdigest.com/places-to-play/driftwood-golf-and-ranch-club-driftwood-front-9
18 https://www.golfdigest.com/places-to-play/dupont-country-club-montchanin-nine
19 https://www.golfdigest.com/places-to-play/elk-valley-golf-elk-valley
20 https://www.golfdigest.com/places-to-play/esplanade-at-azario-lakewood-ranch-esplanade
21 https://www.golfdigest.com/places-to-play/firethorn-golf-club-firehorn-par-3
22 https://www.golfdigest.com/places-to-play/first-tee-northwest-arkansas-first-tee-pebbles-course
23 https://www.golfdigest.com/places-to-play/first-tee-of-the-lowcounty-short-course
24 https://www.golfdigest.com/places-to-play/fonner-view-golf-course-fonner-view
25 https://www.golfdigest.com/places-to-play/forest-dunes-bootlegger
26 https://www.golfdigest.com/places-to-play/fox-hills-golf-course-fox-hills-2
27 https://www.golfdigest.com/places-to-play/fox-river-resort-fox-river
28 https://www.golfdigest.com/places-to-play/frontier-golf-course-frontier
29 https://www.golfdigest.com/places-to-play/gamble-sands-quicksands-course

**Comment by icaraps** [comment]
@hsaginor I think we can get it working with sections again in this case. Each section would be rendered differently eg first section is with images (optional), then the next section is for About content etc. WDYT ?

**Comment by hsaginor** [comment]
@icaraps Sections could work. Not all of them have About section (https://www.golfdigest.com/places-to-play/bayou-oaks-at-city-park-south-course-south-course) but I guess they can put anything as section title. Also, in the right pane I have seen something like a map widget with the location. That could probably be authored with just a google maps link.

**Comment by hsaginor** [comment]
@icaraps and take a look at the cool image slider at the top here https://www.golfdigest.com/places-to-play/forest-dunes-bootlegger :)

**Comment by hsaginor** [comment]
Course pages are imported under this folder https://drive.google.com/drive/u/0/folders/1OudSl2TFxb6fyr6j7KA1UQIb8On-jMAq 
We'll have rename this folder or move the content. cc @icaraps
