### ISSUE TITLE
Import golf club pages

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#243]
For example https://www.golfdigest.com/hot-list/golf-clubs/drivers/srixon-zx7-mk-ii-zx5-mk-ii-zx5-ls-mk-ii

**Comment by hsaginor** [comment]
@icaraps Please take a look here 
https://docs.google.com/document/d/1JPbQfso6ujhbCPBCoH4wi0jQvikRD2ObdI5UJa-jnuc/edit#heading=h.gjdgxs
https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/equipment/hot-list/hot-list-2023/golf-clubs/drivers/ping-g430-max-g430-sft-g430-lst-g430-hl

**Comment by icaraps** [comment]
@hsaginor Thanks ! I created https://github.com/headwirecom/helix-sportsmagazine/issues/280 to follow up with the impl of the club-listing template
