### ISSUE TITLE
Apple podcast missing in articles

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#247]
@hsaginor  For example https://www.golfdigest.com/story/be-right-podcast-new-name-the-loop, there are 2 apple podcasts. This doesn't seem imported see https://gd.headwire.workers.dev/content-v2/the-loop/_default/article/2022/7/be-right-podcast-new-name-the-loop.

**Comment by icaraps** [comment]
<img width="1404" alt="Screenshot 2023-09-18 at 09 55 43" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/fb9c9299-fd94-44a2-a71a-8e65225b20d1">

**Comment by hsaginor** [comment]
@icaraps This has already been fixed in the importer but the content needs to be re-imported. See attached document

[be-right-podcast-new-name-the-loop.docx](https://github.com/headwirecom/helix-sportsmagazine/files/12652268/be-right-podcast-new-name-the-loop.docx)

**Comment by hsaginor** [comment]
This is fixed in new content under /content-v3
