### ISSUE TITLE
Import video pages

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#250]
eg https://www.golfdigest.com/video/major-moments--2023-open-championship/8-things-you-forgot-about-the-2014-open-championship

**Comment by hsaginor** [comment]
@icaraps Do you know what video data we want to import and how do we want to structure it in the document? It would be helpful to create one manually to know what to import.

**Comment by icaraps** [comment]
@hsaginor No I didn't look into details how to model the data in the document. Yes it seems there needs to be a source, a title and description at least ?

**Comment by hsaginor** [comment]
@icaraps See https://docs.google.com/document/d/1OgF-LKQy3WkWf-flA-dQ8Nze2LhdEBgl09RjtBKRM6M/edit#heading=h.gjdgxs
WDYT?

**Comment by icaraps** [comment]
@hsaginor  LGTM but is it always the same player or do we also have to mention the player ?

**Comment by hsaginor** [comment]
@icaraps I am not sure if player changes. I have assumed that could. Also the account id probably doesn't change. But we have to store them somewhere. I just decided to put all this in section block for now and see what you think.

We probably need to create a video pages specific index to render the Related Videos list

**Comment by icaraps** [comment]
> I am not sure if player changes. I have assumed that could.

Yup sounds good

> We probably need to create a video pages specific index to render the Related Videos list 

+1

**Comment by hsaginor** [comment]
@icaraps Video pages are created under content-v3 sub-folder (this will be renamed). I removed the Related Videos subsection since these are not authored on the current site. Those need to be aggregated in some other way (based on folder structure I think).
