### ISSUE TITLE
Inline image, fullscreen images and image captions cannot be differentiated

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#254]
Articles have images that are displayed inline with text like this:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/22e87eee-bfda-4a62-afe7-82a5c0117a46) 
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/030ae0ea-7925-45f3-9171-e45662a1de3e)

And there are also fullscreen images:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/9c79a174-3442-45d6-89f4-94dc600f5c63)
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/be75837a-86f1-48cb-9206-50cf0fa8a5f5)

Within the google doc, there is no way to tell how the image should behave. There is also no way to tell if the `<p>` following a picture should be a image caption or not.

**Comment by hsaginor** [comment]
@DriftingSands @icaraps We had a conversation with Lars Thrieloff from Adobe Engineering a while back about image alignment. Franklin doesn't really support rendering in markup how images are aligned in the google doc without us introducing a block. Also, the importer has no way to pass this information from the original page without creating a block property. 

Let me know how do you want to handle this case.

**Comment by icaraps** [comment]
@hsaginor yes ok to create a block for it, we could simply name it "Asset" ?  We could support variations as class names eg "Asset (fullscreen)" wdyt ?

Something like this:

<img width="671" alt="Screenshot 2023-10-24 at 09 37 11" src="https://github.com/headwirecom/helix-sportsmagazine/assets/6012307/6dadf3af-9af5-4161-b435-8e17a5f67985">

**Comment by hsaginor** [comment]
Fixed with a new import under content-v3 (this folder will be renamed).
