### ISSUE TITLE
Some video embeds have titles and descriptions which aren't imported

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#255]
Video embeds in articles often have a title & description which is nowhere to be found in the google docs, these should probably also be turned into embed blocks when imported.

GolfDigest:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/da763d5d-d3f9-412b-a187-ee442be9c1ba)

helix:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/de4e88df-ed98-454c-aeef-2403872ef87a)

Doc:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/97ead3c7-f38f-4e9b-8c2a-0853518af00c)

**Comment by hsaginor** [comment]
@DriftingSands Can you please add URLs to the original pages and franklin versions to all tickets you open? It saves time not having to search for them.

cc: @icaraps

**Comment by hsaginor** [comment]
@DriftingSands @icaraps 

Here is the re-imported document. This video embed is imported as a block now with an additional row for any markup that comes with it.
https://docs.google.com/document/d/1Xylr4phmOiruwAMssxyCYeLGG83tkPrPxkuR-6t0UWM/edit

Publishing this page in preview it looks like this video is not rendering now. I suspect that the Embed block needs to be fixed to handle this. 
https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v3/courses/default/article/2022/12/national-golf-links-of-america-every-hole-drone

This was only implemented for video embeds (YouTube and Brightcove) and only for a specific case I found (".o-StoryFeature__m-TextWrap") selector. But let me know if you see any other cases.
