### ISSUE TITLE
Google spreadsheet iframe not imported

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#257]
Spreadsheet iframe from https://www.golfdigest.com/story/majors-matrix page is not in the google doc
https://docs.google.com/document/d/1PahsYfnzah3AudPRB_RwDd14tSQBmJOnFg_tn_3rvhs/edit

**Comment by hsaginor** [comment]
@DriftingSands @icaraps 

This was was fixed in issue https://github.com/headwirecom/helix-sportsmagazine/issues/128. 
All new imported content will have an Embed block for any iframe displaying external content. 
https://docs.google.com/document/d/1s4ETdascWfSQtAofnawoYJkOxmH84HZpA2ydJ2OuUdY/edit
