### ISSUE TITLE
Import all Vanity paths

### ISSUE THREAD

**Issue by icaraps** [headwirecom/helix-sportsmagazine#259]
Currently we have only imported 1000 vanity paths as the CF free plan is rate limited.

**Comment by hsaginor** [comment]
@icaraps All newly imported documents under /content-v3 should have the "path" metadata. Is this what you need? Can you take a look please?

**Comment by icaraps** [comment]
@hsaginor Yes thanks a lot ! Created https://github.com/headwirecom/helix-sportsmagazine/issues/279 to follow-up the implementation of the path metadata
