### ISSUE TITLE
Blockquotes are imported as <em>

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#261]
Blockquotes are imported as <em> instead of <blockquote>

![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/08070ef3-3c83-424f-a879-c650c0691119)
https://www.golfdigest.com/story/journey-of-the-claret-jug-cam-smith-games-oldest-trophy

![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/0bd04892-77d3-41dc-80f9-efdab6a3b163)
main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/features/article/2023/6/journey-of-the-claret-jug-cam-smith-games-oldest-trophy

**Comment by hsaginor** [comment]
@DriftingSands This doesn't appear to be an importer issue. This content is imported as blockquote correctly.

Here is the newly imported document 
https://docs.google.com/document/d/1eb6a0v9f_wE4JZvW4DkUWcA2BxFsU3Htx7aBWb-earE/edit
https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v3/golf-news-tours/features/article/2023/6/journey-of-the-claret-jug-cam-smith-games-oldest-trophy

It looks like a blockquote in the document and I see it represented as that in imported Markdown but Franklin seems to render it as em. So, it might be a bug in Franklin (or a "feature" ;))

cc: @icaraps

**Comment by icaraps** [comment]
I just asked on the Discord channel how to properly render a `<blockquote>` when using Google Docs. Maybe it's not supported ?
