### ISSUE TITLE
Podcast embeds are not imported

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#262]
https://www.golfdigest.com/story/the-deepdale-scandal-sandbag-that-changed-golf-calcutta-auctions
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/e450e151-ed72-4447-91ad-dbffbb53d06f)
main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/podcasts/article/2023/6/the-deepdale-scandal-sandbag-that-changed-golf-calcutta-auctions

https://www.golfdigest.com/story/where-pro-golf-has-a-cheating-problem-local-knowledge-podcast
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/097764ba-d137-4119-b342-b55c5b08486e)
main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/golf-news-tours/podcasts/article/2022/9/where-pro-golf-has-a-cheating-problem-local-knowledge-podcast

**Comment by hsaginor** [comment]
This has been fixed. Latest content has been imported under /content-v3 now 
https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v3/golf-news-tours/podcasts/article/2022/9/where-pro-golf-has-a-cheating-problem-local-knowledge-podcast
