### ISSUE TITLE
Anchors are sometimes split/duplicated when imported

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#266]
Anchors that should wrap multiple elements are split when imported, creating duplicate <a> tags that can break some styling

GD site:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/6d637564-c944-4060-b6bf-e779730a8f1e)
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/e8261f50-bba4-4476-9a19-6f8ea420cdb3)

helix site:
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/cd5372a6-1230-4e18-8ca9-33e738ee4d28)
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/7090a7e4-ff7f-44cf-97c5-66f8dcc66aee)

**Comment by hsaginor** [comment]
@DriftingSands Please provide some URLs to documents with this issue as examples.

**Comment by hsaginor** [comment]
@DriftingSands This is not an importer issue as these appear to be represented as a single anchor in the actual document.
![Screen Shot 2023-10-18 at 5 21 24 PM](https://github.com/headwirecom/helix-sportsmagazine/assets/1476638/acf33073-666c-4713-b79b-176f3210e86a)

But Franklin seems to generate these split <a> tags if you look at default markup it generates. I would consider this to be a Franklin bug.

cc: @icaraps
