### ISSUE TITLE
We have no way of supporting custom in-line styles

### ISSUE THREAD

**Issue by DriftingSands** [headwirecom/helix-sportsmagazine#267]
Sometimes GD has custom in-line styles for elements and we have no way of supporting this.
![image](https://github.com/headwirecom/helix-sportsmagazine/assets/68734204/6a02fe4a-ac64-4490-b41e-7036363f34b1)

https://www.golfdigest.com/story/los-angeles-country-club-us-open-final-holes

https://main--helix-sportsmagazine--headwirecom.hlx.page/content-v2/play/courses/_default/article/2023/6/los-angeles-country-club-us-open-final-holes

**Comment by hsaginor** [comment]
@DriftingSands I think this can't really be done in the importer. Inline styles to not transferable to markdown. So, they cannot be imported.

cc: @icaraps

**Comment by icaraps** [comment]
Yes, that's a real bummer ...
