### ISSUE TITLE
Image embed component at top of article body not importing and displaying

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/helix-sportsmagazine#8]
This is only happening for the image embed at the top of the page, not the image embeds within the body of the article. 

![image-embed](https://user-images.githubusercontent.com/51373617/206572612-6141cbff-df43-4929-af82-697ab7365753.png)

URL:
https://docs.google.com/document/d/1gLQm5mWCxLwbKf2pkcQ46FDO3E9PNqKE-n-pI4xCqos/edit

**Comment by hsaginor** [comment]
This issue is fixed. All content will need to be reimported. Also, still need to fix image embed alignment and styling.
