### ISSUE TITLE
"The Loop" navigation is displaying across all sections/entire site

### ISSUE THREAD

**Issue by ehdatheadwire** [headwirecom/helix-sportsmagazine#9]
The top navigation as a whole needs to be examined. Currently, "The Loop" navigation and "Play" sub-nav are displaying across all content. The top navigation should display the correct sections and sub-nav for each section on the landing pages and yes, sub-nav should not display on actual article pages (there is already a ticket in for this.)

![nav-issue](https://user-images.githubusercontent.com/51373617/206571845-3b59213d-879e-404b-843e-1ef6db0d1e2f.png)

**Comment by hsaginor** [comment]
This is fixed on article pages with #4. It doesn't apply to anything else since only article pages have been imported.
